language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:cginternals/backports-ppa'
    packages:
      - gcc-6
      - g++-6
      - xorg-dev
      - libglu1-mesa-dev
      - libsdl2-dev
      - libx11-dev
      - libxcursor-dev
      - libglbinding-dev
      - libglbinding-dbg
      - zlib1g-dev

cache:
  directories:
    - "$HOME/.local"

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script:
  - cd "$TRAVIS_BUILD_DIR"
  - mkdir cbuild && cd cbuild
  - cmake ..
  - make -j4
